version: '3.9'

services:
  postgres-test:
    image: postgres:latest
    container_name: pg-fbs-test
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/postgres-test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_app_test
    networks:
      - appworks

networks:
  appworks:
    driver: bridge
